version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: pilotpanel
      POSTGRES_PASSWORD: superstrongpassword
      POSTGRES_DB: pilotpanel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/New_York
      - PGUSER=pilotpanel
      - PGPASSWORD=superstrongpassword
      - PGDATABASE=pilotpanel
    ports:
      - "1880:1880"
    networks:
      - backend
    volumes:
      - node_red_data:/data
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: yourpgadminpassword
    ports:
      - "5050:80"
    networks:
      - pilotnet
    depends_on:
      - postgres

networks:
  backend:
volumes:
  postgres_data:
  node_red_data: