services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: pilotpanel
      POSTGRES_PASSWORD: superstrongpassword
      POSTGRES_DB: pilotpanel
      TZ: "America/New_York"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pilotnet

  node-red:
    container_name: nodered
    image: nodered/node-red:latest
    environment:
      TZ: "America/New_York"
    ports:
      - "1880:1880"
    networks:
      - pilotnet
    volumes:
      - nodered_data:/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: yourpgadminpassword
    ports:
      - "5050:80"
    networks:
      - pilotnet
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  pilotnet:

volumes:
  postgres_data:
  nodered_data:
  pgadmin_data: